version: '3.9'

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py collectstatic --noinput &&
            python manage.py migrate &&
            uwsgi --socket :9000 --workers 4 --master --enable-threads --module app.wsgi"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  nginx:
    build:
      context: ./proxy
    restart: always
    ports:
      - 8080:8080
    command: >
      sh -c "envsubst < /etc/nginx/default.conf.tpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - static-data:/vol/static

volumes:
  db-data:
  static-data:
